// services/ui/react/src/Home/Home.tsx
import { useState } from 'react';
import { Outlet, useNavigate } from 'react-router';
import {
  AppBar,
  Toolbar,
  IconButton,
  Box,
  useMediaQuery,
  useTheme,
  Icon,
  Tooltip,
  Stack,
} from '@mui/material';
import MenuIcon from '@mui/icons-material/Menu';
import FaceIcon from '@mui/icons-material/Face';
import ExitToAppIcon from '@mui/icons-material/ExitToApp';
import { useAuth } from '../AuthProvider/authContext';
import { ConfirmDialog } from '../ConfirmDialog/ConfirmDialog';
import { SidebarMenu } from './SidebarMenu';
import CoverosLogo from 'assets/coveros-logo.png';

export const Home = () => {
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('md'));
  const [sidenavOpen, setSidenavOpen] = useState(true);
  const [signOutDialogOpen, setSignOutDialogOpen] = useState(false);
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleMenuClick = () => {
    setSidenavOpen(!sidenavOpen);
  };

  const handleSignOut = () => {
    setSignOutDialogOpen(true);
  };

  const handleConfirmSignOut = () => {
    setSignOutDialogOpen(false);
    logout();
    navigate('/login');
  };

  const handleCancelSignOut = () => {
    setSignOutDialogOpen(false);
  };

  return (
    <Stack sx={{ height: '100vh', width: '100vw' }} direction="column">
      <AppBar position="static" color="default" sx={{ mb: '5px' }}>
        <Toolbar>
          <Tooltip title="Menu">
            <IconButton
              edge="start"
              color="inherit"
              aria-label="menu"
              onClick={handleMenuClick}
              id="main-menu-toggle"
            >
              <MenuIcon />
            </IconButton>
          </Tooltip>
          <Box
            component="img"
            src={CoverosLogo}
            alt="Coveros Logo"
            sx={{ height: 48, mr: 2 }}
            id="logo"
          />
          <Box sx={{ flexGrow: 1 }} />
          <Tooltip title={user?.username || ''}>
            <Icon>
              <FaceIcon />
            </Icon>
          </Tooltip>
          <Tooltip title="Sign Out">
            <IconButton
              color="inherit"
              onClick={handleSignOut}
              id="sign-out-button"
              aria-label="Sign Out"
            >
              <ExitToAppIcon />
            </IconButton>
          </Tooltip>
        </Toolbar>
      </AppBar>
      <Stack sx={{ flex: 1, overflow: 'hidden' }} direction="row">
        <SidebarMenu
          open={sidenavOpen}
          onClose={() => setSidenavOpen(false)}
          isMobile={isMobile}
        />

        <Box
          component="main"
          sx={{
            flex: 1,
            overflow: 'auto',
          }}
        >
          <Outlet />
        </Box>
      </Stack>

      <ConfirmDialog
        open={signOutDialogOpen}
        title="Sign out?"
        message="Are you sure you want to sign out?"
        onConfirm={handleConfirmSignOut}
        onCancel={handleCancelSignOut}
        cancelId="cancel-sign-out"
        confirmId="confirm-sign-out"
      />
    </Stack>
  );
};

// services/ui/angular/src/app/home/home.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import {Subject} from 'rxjs';
import {takeUntil} from 'rxjs/operators';
import { AuthService } from '../auth/auth.service';
import {ConfirmDialogService} from '../shared/confirm-dialog/confirm-dialog.service';
import { BreakpointObserver, Breakpoints, BreakpointState } from "@angular/cdk/layout";
import { MatDrawerMode } from "@angular/material/sidenav";

@Component({
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  standalone: false
})
export class HomeComponent implements OnInit, OnDestroy {
  sidenavOpen = true;
  sidenavMode: MatDrawerMode = 'side';
  isMobile = false;
  isXs = false;
  username = '';

  private destroyed$ = new Subject<boolean>();

  constructor(
    private breakpointObserver: BreakpointObserver,
    private authService: AuthService,
    private confirmDialogService: ConfirmDialogService
  ) {}

  ngOnInit(): void {
    this.breakpointObserver
      .observe([Breakpoints.XSmall, Breakpoints.Small])
      .pipe(takeUntil(this.destroyed$))
      .subscribe((state: BreakpointState) => {
        this.isXs = state.breakpoints[Breakpoints.XSmall] ?? false;
        this.isMobile = this.isXs || (state.breakpoints[Breakpoints.Small] ?? false);
        this.sidenavOpen = !this.isMobile;
        this.sidenavMode = (this.isMobile) ? 'over' : 'side';
      });
    const user = this.authService.getLoggedInUser();
    this.username = user.username;
  }

  ngOnDestroy(): void {
    this.destroyed$.next(true);
    this.destroyed$.complete();
  }

  onMenuClick() {
    this.sidenavOpen = !this.sidenavOpen;
  }

  onSignOut() {
    this.confirmDialogService.open({
      title: 'Sign out?',
      message: 'Are you sure you want to sign out?',
      cancelId: 'cancel-sign-out',
      confirmId: 'confirm-sign-out'
    }).subscribe(confirmed => {
      if (confirmed) {
        this.authService.logout();
      }
    });
  }
}

<div class="mat-typography app-container" [class.is-mobile]="isMobile">
  <div>
    <mat-toolbar color="accent">
      <button
        mat-icon-button
        (click)="onMenuClick()"
        id="main-menu-toggle"
        matTooltip="Menu">
        <mat-icon>menu</mat-icon>
      </button>
      <img id="logo" src="assets/coveros-logo.png" alt="Coveros Logo"/>
      <span class="flex-spacer"></span>
      <mat-icon [matTooltip]="username">face</mat-icon>
      <button mat-icon-button
              (click)="onSignOut()"
              id="sign-out-button"
              matTooltip="Sign Out"
              aria-label="Sign Out">
        <mat-icon>exit_to_app</mat-icon>
      </button>
    </mat-toolbar>
  </div>
  <mat-sidenav-container>
    <mat-sidenav
      [mode]="sidenavMode"
      [opened]="sidenavOpen">

      <!--Should be a separate component-->

      <mat-nav-list>
        <h3 matSubheader>Menu</h3>
        <a mat-list-item routerLink="/users" routerLinkActive="active" id="user-menu-item">Users</a>
        <a mat-list-item routerLink="/training" routerLinkActive="active" id="training-menu-item">Training</a>
        <a mat-list-item routerLink="/swagger" routerLinkActive="active" id="swagger-menu-item">API Reference</a>
      </mat-nav-list>

    </mat-sidenav>
    <mat-sidenav-content>
      <router-outlet></router-outlet>
    </mat-sidenav-content>
  </mat-sidenav-container>
</div>
